# Generated by Django 2.0.1 on 2018-01-31 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DancefloorEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('url', models.URLField(unique=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('completed', models.NullBooleanField(default=None)),
            ],
            options={
                'ordering': ['event_date'],
                'verbose_name_plural': 'Dancefloor Events',
            },
        ),
        migrations.CreateModel(
            name='DancefloorEventDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('url', models.URLField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.DancefloorEvent')),
            ],
            options={
                'ordering': ['event_date'],
                'verbose_name_plural': 'Dancefloor Event Details',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(unique=True)),
                ('month', models.DateField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['month'],
                'verbose_name_plural': 'Programs',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('time', models.CharField(blank=True, max_length=500, null=True)),
                ('order', models.SmallIntegerField()),
                ('is_live_set', models.BooleanField(default=False)),
                ('is_closing', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('artists', models.ManyToManyField(to='event.Artist')),
                ('event_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.DancefloorEventDetails')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Room')),
            ],
            options={
                'ordering': ['room', 'order'],
                'verbose_name_plural': 'Slots',
            },
        ),
        migrations.AddField(
            model_name='dancefloorevent',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Program'),
        ),
    ]
