# Generated by Django 2.0.1 on 2018-01-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dancefloorevent',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
