# Generated by Django 2.0.1 on 2018-01-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20180131_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dancefloorevent',
            name='completed',
            field=models.NullBooleanField(default=None),
        ),
    ]
