# Generated by Django 2.0.1 on 2018-02-08 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20180131_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danceflooreventdetails',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='event.DancefloorEvent'),
        ),
    ]
