# Generated by Django 2.0.1 on 2018-02-08 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20180208_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danceflooreventdetails',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_details', to='event.DancefloorEvent'),
        ),
    ]
