# Generated by Django 2.0.1 on 2018-02-08 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20180208_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='event_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='event.DancefloorEventDetails'),
        ),
    ]
