# Generated by Django 2.0.1 on 2018-02-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20180208_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
