# Generated by Django 2.0.1 on 2018-02-08 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_room_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='event.Room'),
        ),
    ]
