# Generated by Django 2.0.1 on 2018-02-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20180208_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='dancefloorevent',
            name='notification_send',
            field=models.BooleanField(default=False),
        ),
    ]
