# Generated by Django 2.0.1 on 2018-02-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20180210_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dancefloorevent',
            old_name='notification_send',
            new_name='is_notification_send',
        ),
        migrations.AddField(
            model_name='dancefloorevent',
            name='is_posted_to_rr',
            field=models.BooleanField(default=False),
        ),
    ]
