# Generated by Django 2.0.1 on 2018-02-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_auto_20180210_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dancefloorevent',
            old_name='completed',
            new_name='is_completed',
        ),
        migrations.AddField(
            model_name='dancefloorevent',
            name='has_timetable',
            field=models.BooleanField(default=False),
        ),
    ]
