# Generated by Django 2.0.1 on 2018-02-12 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_auto_20180212_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='completed',
            new_name='is_completed',
        ),
    ]
