# Generated by Django 2.0.1 on 2018-02-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_auto_20180212_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='dancefloorevent',
            name='custom_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
