# Generated by Django 2.0.1 on 2018-02-21 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_dancefloorevent_custom_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dancefloorevent',
            old_name='custom_name',
            new_name='custom_appendix',
        ),
    ]
